# docker-compose.cloud.yml
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB__PG_USER}
      POSTGRES_PASSWORD: ${DB__PG_PASSWORD}
      POSTGRES_DB: ${DB__PG_DATABASE}
    ports:
      - "127.0.0.1:${DB__PG_PORT}:${DB__PG_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB__PG_USER} -d ${DB__PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS__PORT}:${REDIS__PORT}"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS__PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS__PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

  aiogram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: aiogram-bot
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8000:8000"
    networks:
      - app_network
    restart: unless-stopped
    env_file: .env.cloud
    volumes:
      - ./aiogram_bot_template:/app/aiogram_bot_template

volumes:
  pg_data:
  redis_data:

networks:
  app_network:
    driver: bridge