"""Add enhanced prompt

Revision ID: 4ed9f75ce4ad
Revises: e3270887e993
Create Date: 2025-09-13 18:11:47.578202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed9f75ce4ad'
down_revision: Union[str, Sequence[str], None] = 'e3270887e993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('enhanced_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'enhanced_prompt')
    # ### end Alembic commands ###
