"""add has_used_live_queue to users table

Revision ID: 82f3a3cd79a1
Revises: 5ee257782ce5
Create Date: 2025-10-16 14:23:47.392469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f3a3cd79a1'
down_revision: Union[str, Sequence[str], None] = '5ee257782ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
