"""add has_used_live_queue to users table

Revision ID: 8cf0fb3d6eaf
Revises: 82f3a3cd79a1
Create Date: 2025-10-16 14:30:13.723955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf0fb3d6eaf'
down_revision: Union[str, Sequence[str], None] = '82f3a3cd79a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_used_live_queue', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_used_live_queue')
    # ### end Alembic commands ###
