"""Add sequence generation

Revision ID: b650660b7fc3
Revises: 4ed9f75ce4ad
Create Date: 2025-09-15 11:54:51.271307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b650660b7fc3'
down_revision: Union[str, Sequence[str], None] = '4ed9f75ce4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('sequence_index', sa.Integer(), nullable=True, comment='The 0-indexed position of this image in a photoshoot sequence.'))
    op.add_column('generations', sa.Column('source_generation_id', sa.Integer(), nullable=True, comment='The ID of the previous generation in the sequence, used as a source.'))
    op.create_foreign_key(None, 'generations', 'generations', ['source_generation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generations', type_='foreignkey')
    op.drop_column('generations', 'source_generation_id')
    op.drop_column('generations', 'sequence_index')
    # ### end Alembic commands ###
